package com.interswitch.constant;

public enum UssdStep {
    // Existing
    AIRTIME_INIT, SELECT_ACCOUNT, PURCHASE,

    // Main menu
    MAIN_MENU,

    // Transfer flows
    TRANSFER_MENU,
    TRANSFER_SELF, TRANSFER_SELF_AMOUNT, TRANSFER_SELF_PIN,
    TRANSFER_OTHER_OLIVE, TRANSFER_OTHER_OLIVE_AMOUNT, TRANSFER_OTHER_OLIVE_ACCOUNT, TRANSFER_OTHER_OLIVE_PIN,
    TRANSFER_OTHER_BANK, TRANSFER_OTHER_BANK_AMOUNT, TRANSFER_OTHER_BANK_ACCOUNT, TRANSFER_OTHER_BANK_BANK, TRANSFER_OTHER_BANK_CONFIRM,
    TRANSFER_OTHER_EWALLET, TRANSFER_OTHER_EWALLET_AMOUNT, TRANSFER_OTHER_EWALLET_ACCOUNT, TRANSFER_OTHER_EWALLET_PROVIDER, TRANSFER_OTHER_EWALLET_PIN,

    // Airtime & Data
    AIRTIME_DATA_MENU,
    AIRTIME_SELF, AIRTIME_SELF_AMOUNT,
    AIRTIME_OTHER, AIRTIME_OTHER_PHONE, AIRTIME_OTHER_AMOUNT, AIRTIME_OTHER_PIN,
    DATA_SELF, DATA_SELF_PLAN, DATA_SELF_PIN,
    DATA_OTHER, DATA_OTHER_PHONE, DATA_OTHER_NETWORK, DATA_OTHER_PLAN, DATA_OTHER_PIN,
    AIRTIME_ADVANCE, AIRTIME_ADVANCE_PIN,

    // Bills & Utilities
    BILLS_MENU,
    CABLE_TV, CABLE_PROVIDER, CABLE_SMARTCARD, CABLE_BOUQUET, CABLE_PIN,
    PAY_BILLS, BILLS_CATEGORY, BILLS_PROVIDER, BILLS_REFERENCE, BILLS_AMOUNT, BILLS_PIN,
    BALANCE_CHECK, BALANCE_PIN,

    // Account Services
    ACCOUNT_SERVICES_MENU,
    OPEN_ACCOUNT, OPEN_ACCOUNT_NAME, OPEN_ACCOUNT_DOB, OPEN_ACCOUNT_PHONE, OPEN_ACCOUNT_TYPE, OPEN_ACCOUNT_CONFIRM,
    LOAN_BALANCE, LOAN_BALANCE_PIN,
    GENERATE_TOKEN, TOKEN_AMOUNT, TOKEN_PIN,

    // Security & Settings
    SECURITY_MENU,
    PIN_MANAGEMENT, PIN_MANAGE_MENU,
    CHANGE_PIN, CHANGE_PIN_OLD, CHANGE_PIN_NEW, CHANGE_PIN_CONFIRM,
    RESET_PIN, RESET_PIN_PHONE, RESET_PIN_OTP, RESET_PIN_NEW, RESET_PIN_CONFIRM,
    OPT_IN_OUT, OPT_IN_OUT_MENU,
    OPT_IN, OPT_IN_PIN, OPT_IN_CARD,
    OPT_OUT, OPT_OUT_PIN, OPT_OUT_CARD
}